idem

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -71,7 +71,12 @@ jobs:
           SFML_INSTALL_DIR: 'C:/Program Files (x86)/SFML'
           BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory
         run: |
-          export PATH="/mingw64/bin:$PATH" which cmake || { echo "cmake not found"; exit 1; } cmake -S . -B build -G "MinGW Makefiles" -DSFML_DIR="$SFML_INSTALL_DIR" -DBUILD_WRAPPER_OUT_DIR="$BUILD_WRAPPER_OUT_DIR" -DCMAKE_BUILD_TYPE=Release
+          export PATH="/mingw64/bin:$PATH"
+          if ! which cmake; then
+            echo "cmake not found"
+            exit 1
+          fi
+          cmake -S . -B build -G "MinGW Makefiles" -DSFML_DIR="$SFML_INSTALL_DIR" -DBUILD_WRAPPER_OUT_DIR="$BUILD_WRAPPER_OUT_DIR" -DCMAKE_BUILD_TYPE=Release
 
       # 7
       #- name: Install MinGW
